### ISSUE TITLE
点了开发一直报错

### ISSUE THREAD

**Issue by monw3c** [whatifhappen/feWorkflow#1]
点了开发一直报错，貌似是node安装包有错

**Comment by whatifhappen** [comment]
报错的提示贴一下？

**Comment by monw3c** [comment]
![image](https://cloud.githubusercontent.com/assets/1715568/18045478/8e40740c-6e05-11e6-9c0f-95c66bf55ba3.png)
![image](https://cloud.githubusercontent.com/assets/1715568/18045485/962ec024-6e05-11e6-8ef7-e7c6da3bb769.png)

**Comment by whatifhappen** [comment]
这个问题是因为node版本比较新的缘故，导致fs模块和node-sass的包载入报错，两种解决方案：
A. 降级node环境，使用node.js 4.x版本；
B. 或者命令行进入`/Applications/feWorkflow-wx.app/Contents/Resources/app/node_modules/`, 输入`npm rebuild node-sass`重新创建node-sass的依赖（此时仍有fs模块出错提示，可忽略，直到更新gulp4.0才可修复）
